### PR TITLE
Remote API commands

### PR DESCRIPTION
**Pull request by hexylena**
just pushing progress from this afternoon. This will be so nice to have.

### CODE REVIEW

**Comment by hexylena** [comment]
Ready to go if you want to test them @abretaud. I've written nicer documentation in the apollo library side, but the generated commands' documentation kinda sucks and misses the important bits. I think I need to update command engine to handle this better. Maybe there's some way I can lever sphinx-apidoc and avoid having to have the doc-builder script..

**Comment by abretaud** [comment]
Niiice!
I don't know if I'll have time to test soon, but it's exciting!

**Comment by hexylena** [comment]
No rush, just wanted to let you know it was available. Cc @moffmade if you wanna test too

**Comment by abretaud** [comment]
Oh, sorry, I broke your PR while merging #3 :/

**Comment by hexylena** [comment]
No problem. I'll touch this up later.

**Comment by abretaud** [comment]
I think I'll need this soon, so I updated the PR, I'll check if everything works before merging

**Comment by abretaud** [comment]
Tested, and it works great! @erasche do you want to look at it before merging?
We'll see if we can get https://github.com/GMOD/Apollo/issues/2082 done before releasing a new python-apollo release

**Comment by hexylena** [comment]
Wow, amazed it works still! with not so many patches. I can't approve it, you'll have to.

**Comment by abretaud** [comment]
Yes, I was (happily) surprised too!

**Comment by hexylena** [comment]
Looks fine to me, approve/merge if you like :)

**Comment by abretaud** [comment]
Goooo!

**Pull request merged**
