### PR TITLE
begin to refactor gff3

### PR DESCRIPTION
**Pull request by nathandunn**
- [x] fix organism test 1:

```
FAIL: test_delete_features (test.organism_test.OrganismTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/galaxy-genome-annotation/python-apollo/test/organism_test.py", line 131, in test_delete_features
    assert len(feats_before['features']) > 0
AssertionError: 
```

- [x] fix organism test 2: 

```
Traceback (most recent call last):
  File "/home/travis/build/galaxy-genome-annotation/python-apollo/test/organism_test.py", line 149, in test_delete_features_cn
    assert len(feats_before['features']) > 0
```

- [ ] fix io / download test (or comment out), may need an additional check or delay
```
======================================================================
FAIL: test_export_gff3 (test.io_test.IoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nathandunn/repositories/APOLLO/python-apollo/test/io_test.py", line 24, in test_export_gff3
    assert 'score=["-1335.034872"]' in gff_content
AssertionError: 
    assert 'Merlin\t.\tmRNA\t2\t691\t.\t+\t.' in '##gff-version 3\n##sequence-region Merlin 1 172788\nMerlin\t.\tgene\t2\t691\t.\t+\t.\towner=admin@local.host;ID=a21958bc-3a3c-4e7a-bfb5-ade4fb87f7e4;date_last_modified=2020-06-18;Name=Merlin;date_creation=2020-06-18\nMerlin\t.\tmRNA\t2\t691\t.\t+\t.\towner=admin@local.host;Parent=a21958bc-3a3c-4e7a-bfb5-ade4fb87f7e4;ID=7e5c230d-ff20-4b3d-be49-3d4afb8ad1bc;date_last_modified=2
```

---

- [ ] test command-line for each type below

---

- [ ] validate test for coding gene, exons AND CDS, add score, etc. if there
- [ ] validate test for non-coding gene, exons, but no CDS
- [ ] validate test for coding transcript (same as above)
- [ ] validate test for non-coding transcript (same as above)
- [ ] validate test for pseudogene
- [ ] validate test for single-level feature

---

- [ ] add remaining properties (dbxref, go_annotations, etc. etc., or maybe for another time)

### CODE REVIEW

**Comment by nathandunn** [comment]
@hexylena  / @abretaud  Please feel free to contribute.  Otherwise I will get to it.  

Mostly trying to replicate this:  https://github.com/GMOD/Apollo/blob/develop/tools/data/add_features_from_gff3_to_annotations.pl

**Comment by nathandunn** [comment]
Looking at this code here: 

https://biopython.org/wiki/Gene_predictions_to_protein_sequences

all of the examples use mRNA as top, instead of gene. 

When we use gene at the top, this GFF3 parser completely ignores the rest of the features instead of capturing the structure appropriately.

**Comment by abretaud** [comment]
Thanks! I'll review it fully probably next week!
If you have time (I can do it otherwise!) I'd love to have this function return proper json, with a list of top level features ids and their corresponding apollo internal ids. It could be useful when you load a gff and want to be able to change things on features that were loaded.

**Comment by nathandunn** [comment]
@abretaud Not entirely sure where you want the IDs added (during the download or when added), but I'll be on vacation early next week.  If you open a ticket in Apollo (if its not being returned there) I can add it there.  Otherwise, feel free to add / update whatever you want to and merge at your leisure.

**Comment by abretaud** [comment]
Thanks for your work @nathandunn! I've some changes to fix problems I found with my gff, it should be much better than 4.2.2 now
I'm going to merge this and to release 4.2.3 now, we can always improve it in future releases

**Pull request merged**
