### PR TITLE
reports the correct version now

### PR DESCRIPTION
**Pull request by nathandunn**
typing `arrow --version` gives the version as 4.2.7 and this fixes it

### CODE REVIEW

**Comment by abretaud** [comment]
Good catch thanks!
Do you want a new release with that updated number, or can it wait the next one?

**Comment by nathandunn** [comment]
If we can do it for this one we should. Thanks,

Nathan

**Comment by abretaud** [comment]
We can't replace the published 4.2.10 version, but preparing 4.2.11 in #52

**Comment by nathandunn** [comment]
That sounds great.  Thanks,

Nathan

**Pull request merged**
