### PR TITLE
maximum biopy

### PR DESCRIPTION
**Pull request by hexylena**
anything beyond 1.81 doesn't support 'strand' so, pin;

### CODE REVIEW

**Comment by abretaud** [comment]
numpy wants a python >=3.9, maybe it's time to [update our minimal version](https://github.com/galaxy-genome-annotation/python-apollo/blob/master/setup.py#L38) and the [CI config](https://github.com/galaxy-genome-annotation/python-apollo/blob/master/.github/workflows/test.yml#L21)?

**Comment by hexylena** [comment]
yeah agreed.

**Comment by hexylena** [comment]
this one PR encapsulates so much.. sadness over the churn of libraries lol.

- newer biopython impacts bcbio_gff which isn't maintained so, can't update that
-  python3.11 isn't supported by nose, instead we'll have to switch test harnesses at some point
- numpy wants 3.9 or higher

it's just so much churn for perfectly working software.

**Comment by abretaud** [comment]
thanks! actually there's a new bcbio-gff release I think (at least the recent PR was merged)

**Pull request merged**
